package com.lamu.dao;

import com.lamu.entity.Gallery;
import com.lamu.entity.GalleryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GalleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    long countByExample(GalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int deleteByExample(GalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int insert(Gallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int insertSelective(Gallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    List<Gallery> selectByExample(GalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    Gallery selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Gallery record, @Param("example") GalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Gallery record, @Param("example") GalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Gallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gallery
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gallery record);
}