package com.lamu.dao;

import com.lamu.entity.ProductionPic;
import com.lamu.entity.ProductionPicExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductionPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int countByExample(ProductionPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int deleteByExample(ProductionPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int insert(ProductionPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int insertSelective(ProductionPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    List<ProductionPic> selectByExample(ProductionPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    ProductionPic selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductionPic record, @Param("example") ProductionPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductionPic record, @Param("example") ProductionPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductionPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductionPic record);
}