package com.lamu.dao;

import com.lamu.entity.ProductionKinds;
import com.lamu.entity.ProductionKindsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionKindsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    long countByExample(ProductionKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int insert(ProductionKinds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int insertSelective(ProductionKinds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    List<ProductionKinds> selectByExample(ProductionKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    ProductionKinds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionKinds record, @Param("example") ProductionKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionKinds record, @Param("example") ProductionKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionKinds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_kinds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionKinds record);
}