package com.lamu.dao;

import com.lamu.entity.ProductionStock;
import com.lamu.entity.ProductionStockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    long countByExample(ProductionStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int insert(ProductionStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int insertSelective(ProductionStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    List<ProductionStock> selectByExample(ProductionStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    ProductionStock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProductionStock record, @Param("example") ProductionStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProductionStock record, @Param("example") ProductionStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductionStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductionStock record);
}