package com.lamu.dao;

import com.lamu.entity.ProductionSaled;
import com.lamu.entity.ProductionSaledExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductionSaledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int countByExample(ProductionSaledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int deleteByExample(ProductionSaledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int insert(ProductionSaled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int insertSelective(ProductionSaled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    List<ProductionSaled> selectByExample(ProductionSaledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    ProductionSaled selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductionSaled record, @Param("example") ProductionSaledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductionSaled record, @Param("example") ProductionSaledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductionSaled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production_saled
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductionSaled record);
}