package com.lamu.dao;

import com.lamu.entity.Production;
import com.lamu.entity.ProductionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int countByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int deleteByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int insert(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int insertSelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    List<Production> selectByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    Production selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Production record);
}