package com.lamu.dao;

import com.lamu.entity.Production;
import com.lamu.entity.ProductionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    long countByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int deleteByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int insert(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int insertSelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    List<Production> selectByExample(ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    Production selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Production record, @Param("example") ProductionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Production record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table production
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Production record);
}