package com.lamu.model;

import java.io.Serializable;
import java.util.Date;

public class BookModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.production_id
     *
     * @mbggenerated
     */
    private String productionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.addr
     *
     * @mbggenerated
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.consume
     *
     * @mbggenerated
     */
    private String consume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.uuid
     *
     * @return the value of book.uuid
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.uuid
     *
     * @param uuid the value for book.uuid
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.user_id
     *
     * @return the value of book.user_id
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.user_id
     *
     * @param userId the value for book.user_id
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.production_id
     *
     * @return the value of book.production_id
     * @mbggenerated
     */
    public String getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.production_id
     *
     * @param productionId the value for book.production_id
     * @mbggenerated
     */
    public void setProductionId(String productionId) {
        this.productionId = productionId == null ? null : productionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.count
     *
     * @return the value of book.count
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.count
     *
     * @param count the value for book.count
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.unit
     *
     * @return the value of book.unit
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.unit
     *
     * @param unit the value for book.unit
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.date
     *
     * @return the value of book.date
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.date
     *
     * @param date the value for book.date
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.addr
     *
     * @return the value of book.addr
     * @mbggenerated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.addr
     *
     * @param addr the value for book.addr
     * @mbggenerated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.status
     *
     * @return the value of book.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.status
     *
     * @param status the value for book.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.consume
     *
     * @return the value of book.consume
     * @mbggenerated
     */
    public String getConsume() {
        return consume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.consume
     *
     * @param consume the value for book.consume
     * @mbggenerated
     */
    public void setConsume(String consume) {
        this.consume = consume == null ? null : consume.trim();
    }
}