package com.lamu.model;

import java.io.Serializable;
import java.util.Date;

public class GalleryModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.recommand
     *
     * @mbg.generated
     */
    private Integer recommand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.id
     *
     * @return the value of gallery.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.id
     *
     * @param id the value for gallery.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.name
     *
     * @return the value of gallery.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.name
     *
     * @param name the value for gallery.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.path
     *
     * @return the value of gallery.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.path
     *
     * @param path the value for gallery.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.create_time
     *
     * @return the value of gallery.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.create_time
     *
     * @param createTime the value for gallery.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.recommand
     *
     * @return the value of gallery.recommand
     *
     * @mbg.generated
     */
    public Integer getRecommand() {
        return recommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.recommand
     *
     * @param recommand the value for gallery.recommand
     *
     * @mbg.generated
     */
    public void setRecommand(Integer recommand) {
        this.recommand = recommand;
    }
}