package com.lamu.model;

import java.io.Serializable;
import java.util.Date;

public class ProductionPicModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.production_id
     *
     * @mbggenerated
     */
    private String productionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.pic_addr
     *
     * @mbggenerated
     */
    private String picAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.pic_type
     *
     * @mbggenerated
     */
    private Integer picType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.sort
     *
     * @mbggenerated
     */
    private Integer sort;
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.uuid
     *
     * @return the value of production_pic.uuid
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.uuid
     *
     * @param uuid the value for production_pic.uuid
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.production_id
     *
     * @return the value of production_pic.production_id
     * @mbggenerated
     */
    public String getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.production_id
     *
     * @param productionId the value for production_pic.production_id
     * @mbggenerated
     */
    public void setProductionId(String productionId) {
        this.productionId = productionId == null ? null : productionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.pic_addr
     *
     * @return the value of production_pic.pic_addr
     * @mbggenerated
     */
    public String getPicAddr() {
        return picAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.pic_addr
     *
     * @param picAddr the value for production_pic.pic_addr
     * @mbggenerated
     */
    public void setPicAddr(String picAddr) {
        this.picAddr = picAddr == null ? null : picAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.pic_type
     *
     * @return the value of production_pic.pic_type
     * @mbggenerated
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.pic_type
     *
     * @param picType the value for production_pic.pic_type
     * @mbggenerated
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.sort
     *
     * @return the value of production_pic.sort
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.sort
     *
     * @param sort the value for production_pic.sort
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}