package com.lamu.model;

import java.io.Serializable;
import java.util.Date;

public class ProductionPicModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.production_id
     *
     * @mbg.generated
     */
    private Long productionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.pic_addr
     *
     * @mbg.generated
     */
    private String picAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.pic_type
     *
     * @mbg.generated
     */
    private Integer picType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_pic.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.id
     *
     * @return the value of production_pic.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.id
     *
     * @param id the value for production_pic.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.production_id
     *
     * @return the value of production_pic.production_id
     *
     * @mbg.generated
     */
    public Long getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.production_id
     *
     * @param productionId the value for production_pic.production_id
     *
     * @mbg.generated
     */
    public void setProductionId(Long productionId) {
        this.productionId = productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.pic_addr
     *
     * @return the value of production_pic.pic_addr
     *
     * @mbg.generated
     */
    public String getPicAddr() {
        return picAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.pic_addr
     *
     * @param picAddr the value for production_pic.pic_addr
     *
     * @mbg.generated
     */
    public void setPicAddr(String picAddr) {
        this.picAddr = picAddr == null ? null : picAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.pic_type
     *
     * @return the value of production_pic.pic_type
     *
     * @mbg.generated
     */
    public Integer getPicType() {
        return picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.pic_type
     *
     * @param picType the value for production_pic.pic_type
     *
     * @mbg.generated
     */
    public void setPicType(Integer picType) {
        this.picType = picType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_pic.sort
     *
     * @return the value of production_pic.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_pic.sort
     *
     * @param sort the value for production_pic.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}