package com.lamu.entity;

import java.io.Serializable;
import java.util.Date;

public class Gallery implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gallery.recommand
     *
     * @mbggenerated
     */
    private Integer recommand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.uuid
     *
     * @return the value of gallery.uuid
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.uuid
     *
     * @param uuid the value for gallery.uuid
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.name
     *
     * @return the value of gallery.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.name
     *
     * @param name the value for gallery.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.path
     *
     * @return the value of gallery.path
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.path
     *
     * @param path the value for gallery.path
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.date
     *
     * @return the value of gallery.date
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.date
     *
     * @param date the value for gallery.date
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gallery.recommand
     *
     * @return the value of gallery.recommand
     * @mbggenerated
     */
    public Integer getRecommand() {
        return recommand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gallery.recommand
     *
     * @param recommand the value for gallery.recommand
     * @mbggenerated
     */
    public void setRecommand(Integer recommand) {
        this.recommand = recommand;
    }
}