package com.lamu.entity;

public class ProductionStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.production_id
     *
     * @mbg.generated
     */
    private Integer productionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.id
     *
     * @return the value of production_stock.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.id
     *
     * @param id the value for production_stock.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.stock
     *
     * @return the value of production_stock.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.stock
     *
     * @param stock the value for production_stock.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.unit
     *
     * @return the value of production_stock.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.unit
     *
     * @param unit the value for production_stock.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.production_id
     *
     * @return the value of production_stock.production_id
     *
     * @mbg.generated
     */
    public Integer getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.production_id
     *
     * @param productionId the value for production_stock.production_id
     *
     * @mbg.generated
     */
    public void setProductionId(Integer productionId) {
        this.productionId = productionId;
    }
}