package com.lamu.entity;

import java.io.Serializable;

public class ProductionStock implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.stock
     *
     * @mbggenerated
     */
    private Integer stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_stock.production_id
     *
     * @mbggenerated
     */
    private String productionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.uuid
     *
     * @return the value of production_stock.uuid
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.uuid
     *
     * @param uuid the value for production_stock.uuid
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.stock
     *
     * @return the value of production_stock.stock
     * @mbggenerated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.stock
     *
     * @param stock the value for production_stock.stock
     * @mbggenerated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.unit
     *
     * @return the value of production_stock.unit
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.unit
     *
     * @param unit the value for production_stock.unit
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_stock.production_id
     *
     * @return the value of production_stock.production_id
     * @mbggenerated
     */
    public String getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_stock.production_id
     *
     * @param productionId the value for production_stock.production_id
     * @mbggenerated
     */
    public void setProductionId(String productionId) {
        this.productionId = productionId == null ? null : productionId.trim();
    }
}