package com.lamu.entity;

import java.io.Serializable;

public class ProductionSaled implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_saled.uuid
     *
     * @mbggenerated
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_saled.saled
     *
     * @mbggenerated
     */
    private Integer saled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_saled.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column production_saled.production_id
     *
     * @mbggenerated
     */
    private String productionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_saled.uuid
     *
     * @return the value of production_saled.uuid
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_saled.uuid
     *
     * @param uuid the value for production_saled.uuid
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_saled.saled
     *
     * @return the value of production_saled.saled
     * @mbggenerated
     */
    public Integer getSaled() {
        return saled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_saled.saled
     *
     * @param saled the value for production_saled.saled
     * @mbggenerated
     */
    public void setSaled(Integer saled) {
        this.saled = saled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_saled.unit
     *
     * @return the value of production_saled.unit
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_saled.unit
     *
     * @param unit the value for production_saled.unit
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column production_saled.production_id
     *
     * @return the value of production_saled.production_id
     * @mbggenerated
     */
    public String getProductionId() {
        return productionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column production_saled.production_id
     *
     * @param productionId the value for production_saled.production_id
     * @mbggenerated
     */
    public void setProductionId(String productionId) {
        this.productionId = productionId == null ? null : productionId.trim();
    }
}